name: Main

env:
  node-version: 18.x

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"
      - "lib/**"
      - "tests/**"
      - "Dockerfile"

jobs:
  checks:
    uses: mia-platform/crud-service/.github/workflows/checks.yml@main

  tests:
    needs:
      - checks
    uses: mia-platform/crud-service/.github/workflows/tests.yml@main
    with:
      node-version: $node-version

  release-docker:
    needs:
      - tests
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    uses: mia-platform/crud-service/.github/workflows/release-docker.yml@main
    with:
      version: latest
      push: true
    secrets:
      username: ${{ secrets.BOT_DOCKER_USERNAME }}
      token: ${{ secrets.BOT_DOCKER_TOKEN }}
      security_checks_token: ${{ secrets.CRUD_SERVICE_SYSDIG_CHECK_TRIGGER }}
